vim.keymap.set('n', "vp", 'viwp')
vim.keymap.set('n', '<ESC>', ':noh<CR>:cclose<CR>')
vim.keymap.set('n', 'Y', 'y$')
vim.keymap.set('n', '<C-k>', ':m .-2<CR>==')
vim.keymap.set('n', '<C-j>', ':m .+1<CR>==')
vim.keymap.set('v', '<C-j>', ":m '>+1<CR>gv=gv")
vim.keymap.set('v', '<C-k>', ":m '<-2<CR>gv=gv")
vim.keymap.set('n', '<leader>bd', ':bd<CR>')
vim.keymap.set('n', '<leader>bx', ':%bd<bar>e#<bar>bd#<CR>')
vim.keymap.set('n', '<leader>q', ':wq<CR>')
vim.keymap.set('n', '<leader>w', ':w<CR>')
vim.keymap.set('n', '<leader>e', ':e<CR>')
vim.keymap.set('n', '<leader>r', ':LspRestart<CR>')
vim.keymap.set('n', '<up>', '<nop>')
vim.keymap.set('n', '<down>', '<nop>')
vim.keymap.set('n', '<left>', '<nop>')
vim.keymap.set('n', '<right>', '<nop>')
vim.keymap.set('n', '<leader>sv', ':vsplit<CR>')
vim.keymap.set('n', '<leader>sh', ':split<CR>')
vim.keymap.set('n', '<up>', ':resize +2<CR>')
vim.keymap.set('n', '<down>', ':resize -2<CR>')
vim.keymap.set('n', '<left>', ':vertical resize -2<CR>')
vim.keymap.set('n', '<right>', ':vertical resize +2<CR>')
vim.keymap.set('n', '<leader>rr', '<C-w>r')
vim.keymap.set('n', '<leader>=', '<C-w>=')
vim.keymap.set('n', '<leader>l', ':wincmd l<CR>')
vim.keymap.set('n', '<leader>k', ':wincmd k<CR>')
vim.keymap.set('n', '<leader>j', ':wincmd j<CR>')
vim.keymap.set('n', '<leader>h', ':wincmd h<CR>')
vim.keymap.set("n", "J", "mzJ`z") -- keeps cursor on start of line when using J
vim.keymap.set("n", "<C-d>", "<C-d>zz") -- keeps cursor in middle when using CTRL-d
vim.keymap.set("n", "<C-u>", "<C-u>zz") -- keeps cursor in middle when using CTRL-u
vim.keymap.set("x", "<leader>p", [["_dP]])
vim.keymap.set({ "n", "v" }, "<leader>d", [["_d]])
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set("n", "<leader>Y", [["+Y]])
vim.keymap.set("n", "<leader>f", vim.lsp.buf.format)
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n", "<leader>x", "<cmd>!chmod +x %<CR>", { silent = true })
