-- transparent
vim.cmd([[au VimEnter * hi Normal guibg=#000000 guifg=None]])
vim.cmd([[au VimEnter * hi NormalNC guibg=None guifg=None]])
vim.cmd([[au VimEnter * highlight Pmenu none]]) -- sets autocomplete suggestions to to transparent
vim.cmd([[au VimEnter * hi StatusLine guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi StatusLineNC guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi LineNr guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi Folded guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi NonText guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi SpecialKey guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi VertSplit guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi SignColumn guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi EndOfBuffer guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi TelescopeNormal guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi TelescopeBorder guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi NvimTreeNormal guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi NvimTreeNormalNC guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi NvimTreeVertSplit guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi NvimTreeStatusLine guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi NvimTreeStatusLineNC guibg=none ctermbg=none guifg=none]])
vim.cmd([[au VimEnter * hi ZenBg guibg=none ctermbg=none guifg=none]])
